### ISSUE TITLE
Compile panics on integer division in constant expression

### ISSUE THREAD

**Issue by TheCount** [antonmedv/expr#138]
```go
package main

import (
	"fmt"
	"github.com/antonmedv/expr"
)

func main() {
	env := map[string]interface{}{}

	code := `1/0`

	program, err := expr.Compile(code, expr.Env(env))
	if err != nil {
		panic(err)
	}

	output, err := expr.Run(program, env)
	if err != nil {
		panic(err)
	}

	fmt.Println(output)
}
```

https://play.golang.org/p/CIeZgpJe2lj

Expected behaviour:
Either `expr.Compile` returns an error, or it succeeds and `expr.Run` returns an error.

Actual behaviour:
`expr.Compile` panics with a divide by zero error:
````
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/antonmedv/expr/optimizer.(*fold).Exit(0xc00002c06a, 0xc00000c0e0)
	/tmp/gopath651672835/pkg/mod/github.com/antonmedv/expr@v1.8.8/optimizer/fold.go:68 +0xc34
github.com/antonmedv/expr/ast.(*walker).walk(0xc000068e60, 0xc00000c0e0)
	/tmp/gopath651672835/pkg/mod/github.com/antonmedv/expr@v1.8.8/ast/visitor.go:45 +0x4be
github.com/antonmedv/expr/ast.Walk(...)
	/tmp/gopath651672835/pkg/mod/github.com/antonmedv/expr@v1.8.8/ast/visitor.go:18
github.com/antonmedv/expr/optimizer.Optimize(0xc00000c0e0, 0xc00018a000, 0x5dea20, 0x57d240)
	/tmp/gopath651672835/pkg/mod/github.com/antonmedv/expr@v1.8.8/optimizer/optimizer.go:12 +0xde
github.com/antonmedv/expr.Compile(0x5aaffb, 0x3, 0xc000068f60, 0x1, 0x1, 0x406065, 0xc00005e058, 0x0)
	/tmp/gopath651672835/pkg/mod/github.com/antonmedv/expr@v1.8.8/expr.go:167 +0x291
main.main()
	/tmp/sandbox661009204/prog.go:13 +0x8d
````

**Comment by antonmedv** [comment]
Yes, this is a bug as optimizer trying to fold this expression. Will fix it.

**Comment by antonmedv** [comment]
Fixed in https://github.com/antonmedv/expr/releases/tag/v1.8.9
